name: Hetzner Cloud Projects
description: Unofficial tool to manage projects and API tokens in Hetzner Cloud
inputs:
  action:
    description: One of create|delete
    default: create
    required: true
  name:
    description: Name of project to create or delete.
    required: true
  ephemeral:
    description: (Default 'true') If action is 'create', delete the Hetzner Cloud project (and all resources in it) at the end of the run.
    default: 'true'
    required: true
runs:
  using: docker
  image: ghcr.io/samcday/hcloud-project-manager@sha256:33515a20ec5dfac3616456ecf3cdfad0d7bd8b51ea822f1f79623d92d697111a
  args:
    - ${{ inputs.name }}
    - ${{ inputs.action }}
  entrypoint: /actions-entrypoint.sh
  post-entrypoint: /actions-cleanup.sh
  post-if: contains(inputs.action, 'create') # && inputs.ephemeral == 'true'
