name: Build Image

on:
  push:
    branches:
      - 'main'

jobs:
  image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/hcloud-project-manager:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - uses: docker/build-push-action@v2
        with:
          context: .
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/hcloud-project-manager:cargo-${{ hashFiles('Cargo.lock') }},mode=max
          target: deps
