name: test self
on:
  workflow_run:
    workflows: ["Build Image"]
    branches: [main]
    types: [completed]
jobs:
  selftest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./
        with:
          name: actions-test-${{ github.run_id }}
      - run: sleep 60
